### ISSUE TITLE
Implementar caixa dels talps petits

### ISSUE THREAD

**Issue by krypth0n** [EnginyeriaSofwareUB/ES2017A2#100]
En la pantalla de joc han d'aparèixer els talps de cada jugador i l'estat en el que estan (vius o morts). Aquesta informació serà visualitzada a la part superior de la pantalla.

Estimació d'hores: 5h
Real: 8h 9/12

**Comment by borgue95** [comment]
Guillem, fes que el talp actual tingui alguna espècie de glow ja sigui al ninot i/o al número, però que sigui visible per l'usuari, per tal de saber qui està jugant.
