### ISSUE TITLE
Cambiar barra de vida

### ISSUE THREAD

**Issue by MadScientist96** [EnginyeriaSofwareUB/ES2017A2#103]
Cambiar la barra de vida y añadir el nuemro del pj en la barra de vida
Estimacion: 2 horas
Real: 5h

**Comment by MadScientist96** [comment]
(poner % de vida si eso)

**Comment by borgue95** [comment]
Cal arreglar el següent:
- La barra de vida es gira quan el personatge es gira. No s'hauria de girar
