### ISSUE TITLE
Crear los objetos intangibles y las nubes

### ISSUE THREAD

**Issue by bogdan-marcut** [EnginyeriaSofwareUB/ES2017A2#12]
Crear una nube que se mueva de un punto a otro

Estimación: 4h

**Comment by bogdan-marcut** [comment]
Movido en Work in Progress para añadir las funcionalidades nuevas discutidas en la reunión

**Comment by krypth0n** [comment]
La primera versión se han contabilizado 6 horas contando el tiempo de documentación y visualización de tutoriales para poder empezar la implementación y diferentes problemas con el git que hicieron repetir faena ya hecha.
Ahora se ha propuesto actualizar el código con unas mejoras. Para esto se contabilizan 2 horas.
