### ISSUE TITLE
Crear un timer que envia un evento cuando ha acabado

### ISSUE THREAD

**Issue by bogdan-marcut** [EnginyeriaSofwareUB/ES2017A2#14]
Funciones del timer: start, stop, reset

Estimación: 4h
Tiempo real: 6h

**Comment by bogdan-marcut** [comment]
En que estado se encuentra la tarea?

**Comment by Acots96** [comment]
Funciones del timer implementadas en el script TimerGame.cs

**Comment by Acots96** [comment]
Timer definitivo creado e implementado: Es un contador que se va incrementando a cada actualización del juego hasta que llega al límite establecido y actualiza un booleano. Mientras, desde Turn.cs se comprueba continuamente en un bucle si el booleano se ha actualizado. Cuando sea true acabará el turno.
