### ISSUE TITLE
Definir el puntero

### ISSUE THREAD

**Issue by bogdan-marcut** [EnginyeriaSofwareUB/ES2017A2#15]
Implementar clase Puntero para luego poder estimar la trayectoria que cogerá el proyectil.

Tiempo estimado: 1 hora

Tiempo real dedicado a la tarea: 40 minutos

**Comment by bogdan-marcut** [comment]
En que estado se encuentra la tarea?

**Comment by pamplins** [comment]
Finalizada pero todavía necesaria para el Projectile.
