### ISSUE TITLE
Creacion del proyectil

### ISSUE THREAD

**Issue by bogdan-marcut** [EnginyeriaSofwareUB/ES2017A2#16]
Hay que definir un proyectil que se lanza des de la posición del jugador en el sentido del ratón

Estimación: 7 horas aproximadamente

Tiempo real dedicado a la tarea: 8 hoars

**Comment by bogdan-marcut** [comment]
En que estado se encuentra la tarea?

**Comment by pamplins** [comment]
En progreso. Falta poder lanzar el proyectil por cada turno. Actualmente lo hacen los 2 en todos los turnos a la vez. Problema para comentar hoy personalmente si es posible.
