### ISSUE TITLE
Esbozo de los elementos UI de la pantalla de juego

### ISSUE THREAD

**Issue by bogdan-marcut** [EnginyeriaSofwareUB/ES2017A2#26]
Estimación: 4h

**Comment by bogdan-marcut** [comment]
Elementos UI pantalla de juego
-timer
-jugador actual
-personaje seleccionado
-proyectil seleccionado
-numero de balas
-personajes de todos los jugadores (marcar si estan vivos o no)
-opcional: siguiente personaje a jugar

Elementos de cada personaje:
-vida (actual sobre total)
-nombre
-powerbar (decidido en clase)

Elementos inventario:
-proyectiles comprados (habilitados y deshabilitados)
-balas de cada proyectil
-proyectil seleccionado

**Comment by bogdan-marcut** [comment]
En que estado se encuentra la tarea?

**Comment by borgue95** [comment]
Iteració 1 sobre l'esbós: temps emprat: 3h
Temps esperat per la següent iteració: 1h

Deixo aquí una primerenca versió de l'esbós perquè em digueu què us sembla. Coses que falten: La foto dels jugadors a dreta i esquerra del timer. Amb la foto s'indicarà el torn. Barra de vida dels personatges i barra de llançament (per indicar direcció i força). 

La imatge del talp és provisional també. És una prova que vaig fer. 

Inventari: l'hortalissa seleccionada tindrà un quadrat de color vermell. L'hortalissa de la qual no en quedin exemplars, es mostrarà en blanc i negre i amb un 0 de quantitat. Els forats de l'inventari que no tinguin hortalissa (perquè el jugador només ha comprat 5 hortalisses diferents), es mostraran en gris i sense número. Quan al jugador li toqui fer el torn, podrà seleccionar l'hortalissa amb el ratolí. Tinc pensat que deixant el ratolí una estona sobre l'hortalissa surti una bafarada amb les característiques. 
El quadre de l'inventari hauria de ser un xic més gran. Si algú té alguna suggerència d'importància, que deixi un comentari i me'l llegiré.

Deixaré la informació completa quan l'esbós sigui definitiu. 

![sketches](https://user-images.githubusercontent.com/17471172/31546525-f5c55578-b023-11e7-9932-6ac39ff6f147.jpg)

**Comment by borgue95** [comment]
2na iteració sobre el disseny: temps emprat: 2h

Abans de tot, tinc un internet molt dolent aquests dies. La captura és la que és:
![screen shot 2017-10-14 at 13 07 25](https://user-images.githubusercontent.com/17471172/31575176-c4dbef2c-b0e0-11e7-82f0-b78533e3cd56.png)

L'animal que està efectuant el torn estarà repassat amb una silueta: verda si és un animal aliat i vermella si és un animal enemic. En tot cas, només hi podrà haver, en un temps determinat, una (o cap - entre rondes) siluetes marcades a tot el terreny de joc.

Cada animal té una barra de vida associada. El color no depèn de la vida que té, sinó del bàndol: verda pels aliats i vermella pels enemics. 

La barra de potència, aquesta tant esquifida i allargada (potser seria bo canviar-li l'aspect ratio) és una barra que apareixerà quan el jugador vulgui disparar. Com més temps tingui el cursor premut, més part de la barra s'anirà omplint. Quan arribi el màxim (vermell) tindrà un temps per poder disparar; si passat el temps no ha fet res, es cancel·larà el llançament i podrà tornar a llançar. Si deixa de prémer amb el ratolí abans que es cancel·li el llançament, es dispararà en la direcció que és determinada per la posició del ratolí i la posició de l'animal. 

L'inventari. S'ha comentat de fer que l'inventari sigui un pop-up. L'avantatge és que és més fàcil fer que enlloc de 6 elements per personatge, en siguin més. L'inconvenient que crec que té més pes, és que quan es visualitza l'inventari, el cronòmetre corre i es perd la visió del camp de batalla. Per tant, el que proposo és que l'inventari estigui a les cantonades inferiors de la pantalla. 
Clicar sobre un objecte, fa que se seleccioni si encara queden exemplars (numeret > 0). De les hortalisses que no queden exemplars, es mostraran en escala de grisos. Dels llocs que no hi hagi hortalissa (perquè l'usuari ha comprat menys de 6 tipus diferents), quedaran en gris i sense el numeret. En cada llançada, es restarà 1 (en principi) al numeret de l'hortalissa seleccionada. 

Resum dels personatges. A la part superior de la pantalla hi ha una llista amb tots els personatges que participen al camp de batalla, separats per equip. Ara són tots iguals perquè només tenim un sol animal; quan hi hagi més varietat, cada ninotet de la part superior es correspondrà a un únic animal del camp. Quan l'animal mori, se li posarà una creu (on un senyal de prohibit) a sobre per indicar que tal animal ja no està disponible. 

He introduït un botó per pausar el joc. Queda pendent encara fer l'esbós i el disseny de la pantalla de pausa i de victòria. 

El talp que hi ha representat a la foto és una prova que he estat fent. No està ni molt menys acabat. Per ara, només tenia això, però per un esbós n'hi ha més que suficient. El background, és evident que és súper provisional. No serà aquest ni molt menys. 

Hi ha un tiquet (issue) al backlog per fer bé les fotos de les hortalisses. De moment he fet aquestes dues ràpid i corrents. En vindran més i de més qualitat. 

Em sembla que no m'he deixat res de comentar aquí.

**Comment by pausanchezv** [comment]
I el casc groc? Van a treballar a la construcció els talps o que? Jajajaja

Bona feina, està xulo!

**Comment by bogdan-marcut** [comment]
Pendiente de confirmar el diseño en la planificación del siguiente sprint

**Comment by borgue95** [comment]
Actualització. 

Es va acordar donar més informació sobre el que està passant i que fos clara i concisa. Així doncs, es va decidir que l'inventari fos un pop-up per evitar tapar terreny de joc, es va decidir mostrar clarament quin és l'ordre que juguen els animals i quin és el que està jugant actualment. També es va decidir que s'haurien de mostrar de quin jugador és cada talp. Aquest n'és el resultat:

![ingame2](https://user-images.githubusercontent.com/17471172/32134185-161982ca-bbe8-11e7-8734-1f4cb5f651b2.jpg)

i el pop-up de l'inventari:

![ingame2_popup](https://user-images.githubusercontent.com/17471172/32134187-2039178e-bbe8-11e7-9c93-e0ce2b2f7a2b.jpg)
