### ISSUE TITLE
Esbozo de la pantalla de selección de armas 

### ISSUE THREAD

**Issue by bogdan-marcut** [EnginyeriaSofwareUB/ES2017A2#27]
Estimación: 1h

**Comment by borgue95** [comment]
Esbós:
https://www.draw.io/#G0B2p8lUNDBU_COS1LeVI1VGxQU3c

**Comment by borgue95** [comment]
Us deixo l'esbós. Pantalla que veuran quan seleccionin hortalisses
![seleccio_base](https://user-images.githubusercontent.com/17471172/31320193-9aa8c74e-ac70-11e7-9b6a-f5e744c2492d.jpg)
Quan l'usuari faci clic sobre una hortalissa per comprar-la, apareixerà aquest popup. Quan l'usuari incrementi el nombre d'hortalisses, els diners del fons disminuiran (preliminarment) amb un highlight perquè l'usuari ho vegi (ja sigui canviant el color, fent un zoom in/out ràpid, etc). Si l'usuari cancel·la, no perd diners; si l'usuari compra, se li resten. Quan l'usuari compra una hortalissa, s'afegeix aquesta a l'inventari corresponent. Si no existeix, s'afegeix; si existeix, s'incrementa el numeret que està dins la rodoneta. 
La selecció, tal com es va acordar, és per torns; primer un, després l'altre. El torn acaba quan l'usuari compra. Queda per determinar quan s'acaben els torns de compra; la manera més lògica seria donar 6 torns per cada usuari (o fins que es quedin sense diners). Si no, la compra pot ser interminable; o bé, simplement deixar que es gastin tots els diners; o fins que cliquin a continuar. Cal decidir-ho quan s'implementi la pantalla.
![seleccio_popup](https://user-images.githubusercontent.com/17471172/31320192-97ec8072-ac70-11e7-8734-9cd1feefde1f.jpg)

**Comment by bogdan-marcut** [comment]
Dejamos esto como versión final del esbozo.
