### ISSUE TITLE
Esbozo de la pantalla de selección de variables del juego

### ISSUE THREAD

**Issue by borgue95** [EnginyeriaSofwareUB/ES2017A2#28]
Estimación: 1h

**Comment by bogdan-marcut** [comment]
Publica porfa una foto del esbozo para tener una referencia.

**Comment by borgue95** [comment]
![initial_vars_select](https://user-images.githubusercontent.com/17471172/31504350-747191dc-af72-11e7-8ef9-36d512ee7b2b.jpg)

Pantalla de selecció de variables del joc. Aquesta pantalla apareix just després de clicar el botó play de la pantalla principal. 

Té un slider seccionat en 6 parts per seleccionar el nombre d'animals per jugador i un slider per seleccionar el nombre de monedes que es podran utilitzar per jugar. Proposo que el nombre de monedes vagi de 10 en 10, definint un inici diferent de 0 i un final. Aquests dos valors s'haurien de poder ajustar més endavant al codi quan comencem a fer les primeres proves. 

La foto de perfil i el nom d'usuari no s'haurien de poder modificar en aquesta pantalla.
