### ISSUE TITLE
Pantalla Pause

### ISSUE THREAD

**Issue by pausanchezv** [EnginyeriaSofwareUB/ES2017A2#56]
Deixo la pantalla de pause a l'espera que la validi l'scrum master!

![pantalla_pause](https://user-images.githubusercontent.com/16424328/31863859-ffa442f2-b753-11e7-9f03-620b4eabb080.png)

**Comment by bogdan-marcut** [comment]
No habrá fondo de pantalla. Pondremos un container transparente/oscuro por toda la pantalla de juego
